name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - sqlalchemy=1.4
  - pip
  - pip:
      - hummingbot
      - numpy==1.26.4
      - streamlit==1.33.0
      - watchdog
      - python-dotenv
      - plotly
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta==0.3.14b
      - pyyaml
      - jupyter
      - optuna
      - optuna-dashboard
      - pathlib
      - st-pages
      - streamlit-elements==0.1.*
      - streamlit-authenticator==0.3.2
      - pydantic==1.10.4
      - flake8
      - isort
      - pre-commit

      - huggingface_hub
      - -f https://github.com/svrvt/guidance/archive/dev.tar.gz
      - -f https://github.com/abetlen/llama-cpp-python/archive/main.tar.gz

      # - -f git+https://github.com/svrvt/guidance.git@dev
      # - --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
      # - llama-cpp-python
