name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - sqlalchemy=1.4
  - pip
  - pip:
      - hummingbot
      - numpy==1.26.4
      - streamlit==1.33.0
      - watchdog
      - python-dotenv
      - plotly
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta==0.3.14b
      - pyyaml
      - pathlib
      - st_pages
      - streamlit-elements==0.1.*
      - streamlit-authenticator==0.3.2
      - pydantic==1.10.4
      - flake8
      - isort
      - pre-commit

      - huggingface_hub
      - -f git+https://github.com/svrvt/guidance.git@dev
      # - -f https://github.com/svrvt/guidance/archive/dev.zip

      # - -f git+https://github.com/abetlen/llama-cpp-python.git#egg=llama-cpp-python
      # - -f https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp310-cp310-linux_x86_64.whl
      # - --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
      # - llama-cpp-python
